version: '3.9'

services:
  db:
    image: postgres
    restart: on-failure 
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
   driver: local
